#!/usr/bin/env python3
"""Generate hard-coded dual-port twiddle ROM for N=256 over q=3329 in Montgomery form."""

from pathlib import Path

Q = 3329
N = 256
OMEGA = 17         # primitive 256-th root of unity modulo 3329
R = (1 << 16) % Q  # Montgomery R mod q


def montgomery_twiddles() -> list[int]:
    vals: list[int] = []
    x = 1
    for _ in range(N):
        vals.append((x * R) % Q)
        x = (x * OMEGA) % Q
    return vals


def emit_rom(values: list[int]) -> str:
    lines: list[str] = []
    lines.append("`timescale 1ns/1ps")
    lines.append("")
    lines.append("// Auto-generated by hardware/gen_ntt_twiddle_rom.py")
    lines.append("// Twiddle ROM for 256-point NTT over q=3329 in Montgomery form.")
    lines.append("module ntt_twiddle_rom_x256 (")
    lines.append("    input  logic [7:0]   addr_a,")
    lines.append("    input  logic [7:0]   addr_b,")
    lines.append("    output logic [15:0]  dout_a,")
    lines.append("    output logic [15:0]  dout_b")
    lines.append(");")
    lines.append("    logic [15:0] rom [0:255];")
    lines.append("")
    lines.append("    initial begin")
    for i, v in enumerate(values):
        lines.append(f"        rom[{i}] = 16'd{v};")
    lines.append("    end")
    lines.append("")
    lines.append("    always_comb begin")
    lines.append("        dout_a = rom[addr_a];")
    lines.append("        dout_b = rom[addr_b];")
    lines.append("    end")
    lines.append("")
    lines.append("    property p_addr_a_bounds;")
    lines.append("        @(*) (addr_a < 8'd256);")
    lines.append("    endproperty")
    lines.append("    property p_addr_b_bounds;")
    lines.append("        @(*) (addr_b < 8'd256);")
    lines.append("    endproperty")
    lines.append("    assert property (p_addr_a_bounds) else $fatal(1, \"ROM addr_a OOB\");")
    lines.append("    assert property (p_addr_b_bounds) else $fatal(1, \"ROM addr_b OOB\");")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    values = montgomery_twiddles()
    out = Path(__file__).resolve().parent / "ntt_twiddle_rom_x256.sv"
    out.write_text(emit_rom(values), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
