#!/usr/bin/env bash
set -euo pipefail

log() { printf '[toolchain-worker] %s\n' "$*"; }
fail() { printf '[toolchain-worker][error] %s\n' "$*" >&2; exit 1; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_DIR="${ROOT_DIR}/artifacts/toolchain-output"
PUBLISH_DIR="${ARTIFACT_DIR}/output"
PACKAGE_DIR="${ARTIFACT_DIR}/packages"

mkdir -p "${PUBLISH_DIR}" "${PACKAGE_DIR}"

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export NUGET_XMLDOC_MODE=skip
export HTTP_PROXY=
export HTTPS_PROXY=
export NO_PROXY='*'

CACHE_ROOT="${ROOT_DIR}/.nuget/packages"
mkdir -p "${CACHE_ROOT}"

SOLUTION_PATH="${ROOT_DIR}/src/NfcReader/NfcReader.sln"
[[ -f "${SOLUTION_PATH}" ]] || fail "solution not found: ${SOLUTION_PATH}"

if ! command -v dotnet >/dev/null 2>&1; then
  fail 'dotnet SDK is required on the toolchain worker but was not found'
fi

log "using SDK $(dotnet --version)"
log 'restoring dependencies using local cache and internal sources only'
dotnet restore "${SOLUTION_PATH}" \
  --packages "${CACHE_ROOT}" \
  --ignore-failed-sources

log 'building solution deterministically in Release configuration'
dotnet build "${SOLUTION_PATH}" \
  -c Release \
  --no-restore \
  -p:ContinuousIntegrationBuild=true \
  -p:Deterministic=true \
  -p:RestorePackages=false

publish_candidate="${ROOT_DIR}/src/NfcReader/NfcReader.csproj"
if [[ ! -f "${publish_candidate}" ]]; then
  publish_candidate="${ROOT_DIR}/src/NfcReader/NfcReader.Worker/NfcReader.Worker.csproj"
fi

if [[ -f "${publish_candidate}" ]]; then
  log "publishing ${publish_candidate}"
  dotnet publish "${publish_candidate}" \
    -c Release \
    --no-restore \
    -p:ContinuousIntegrationBuild=true \
    -p:Deterministic=true \
    -o "${PUBLISH_DIR}"
else
  log 'no publish candidate found; skipping dotnet publish'
fi

pack_if_present() {
  local project_path="$1"
  local label="$2"

  if [[ -f "${project_path}" ]]; then
    log "packing ${label}: ${project_path}"
    dotnet pack "${project_path}" \
      -c Release \
      --no-restore \
      -p:ContinuousIntegrationBuild=true \
      -p:Deterministic=true \
      -o "${PACKAGE_DIR}"
  else
    log "optional package ${label} not present; skipping"
  fi
}

pack_if_present "${ROOT_DIR}/src/NfcReader/NfcReader.csproj" 'NfcReader'
pack_if_present "${ROOT_DIR}/src/NfcReader.Tools/NfcReader.Tools.csproj" 'NfcReader.Tools'

find "${ROOT_DIR}/src/NfcReader" -type f -name '*.nupkg' -print -exec cp {} "${PACKAGE_DIR}" \;

(
  cd "${ARTIFACT_DIR}"
  mapfile -t files < <(find output packages -type f | sort)
  if [[ ${#files[@]} -eq 0 ]]; then
    fail 'no build artifacts were generated by the toolchain worker'
  fi
  sha256sum "${files[@]}" > SHA256SUMS.txt
  tar -czf package.tar.gz output packages SHA256SUMS.txt
)

log "artifact package ready at ${ARTIFACT_DIR}/package.tar.gz"
