TOPLEVEL_LANG = verilog
SIM ?= icarus

VERILOG_SOURCES = $(PWD)/../../hardware/ntt_butterfly.sv
TOPLEVEL = ntt_butterfly
MODULE = test_ntt_butterfly

include $(shell cocotb-config --makefiles)/Makefile.sim
