#!/usr/bin/env bash
set -euo pipefail

# Bootstrap local developer environment for IATO_V7:
# - writes an env file with stable defaults
# - installs/activates .NET SDK via existing helper
# - installs Lean/Lake via existing helper

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.iato"

DOTNET_VERSION="${DOTNET_VERSION:-8.0.404}"
PYTEST_VERSION="${PYTEST_VERSION:-9.0.2}"

write_env_file() {
  cat > "${ENV_FILE}" <<ENV
# Generated by scripts/setup-lake-dotnet-env.sh
export DOTNET_VERSION="${DOTNET_VERSION}"
export PYTEST_VERSION="${PYTEST_VERSION}"

export DOTNET_ROOT="\${DOTNET_ROOT:-\$HOME/.dotnet}"
export PATH="\$DOTNET_ROOT:\$DOTNET_ROOT/tools:\$HOME/.elan/bin:\$PATH"

# Lean/Lake defaults
export ELAN_HOME="\${ELAN_HOME:-\$HOME/.elan}"
export LEAN_ABORT_ON_PANIC="\${LEAN_ABORT_ON_PANIC:-1}"
export LEAN_PATH="\${LEAN_PATH:-${ROOT_DIR}/IATO_V7/.lake/packages}"
export LAKE_NO_CACHE="\${LAKE_NO_CACHE:-0}"
ENV
}

run_dotnet_setup() {
  echo "[setup] configuring dotnet (version=${DOTNET_VERSION})"
  DOTNET_VERSION="${DOTNET_VERSION}" PYTEST_VERSION="${PYTEST_VERSION}" \
    bash "${ROOT_DIR}/scripts/setup-dotnet-lts.sh"
}

run_lake_setup() {
  echo "[setup] configuring lean/lake"
  bash "${ROOT_DIR}/IATO_V7/scripts/install_lake.sh"
}

main() {
  write_env_file
  echo "[setup] wrote env file: ${ENV_FILE}"

  run_dotnet_setup
  run_lake_setup

  echo "[setup] done"
  echo "[setup] next: source ${ENV_FILE}"
}

main "$@"
