services:
  iato-v7:
    image: docker.io/leanprover/lean4:stable
    working_dir: /workspace
    environment:
      - ELAN_HOME=${ELAN_HOME:-/root/.elan}
      - LEAN_ABORT_ON_PANIC=${LEAN_ABORT_ON_PANIC:-1}
      - LEAN_PATH=${LEAN_PATH:-/workspace/.lake/packages}
      - LAKE_NO_CACHE=${LAKE_NO_CACHE:-0}
      - PODMAN_USERNS=${PODMAN_USERNS:-keep-id}
      - COMPOSE_DOCKER_CLI_BUILD=${COMPOSE_DOCKER_CLI_BUILD:-1}
    volumes:
      - ./:/workspace:Z
    command: >-
      /bin/sh -lc "lake update && lake build && lake test && lake exe cache && lake aot"
