name: build

on:
  workflow_dispatch:

env:
  INSTALL_RETRIES: "3"
  LEAN_TOOLCHAIN: stable

jobs:
  package-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lean
    steps:
      - uses: actions/checkout@v4

      - name: Normalize CI env variables
        run: ../scripts/normalize_ci_env.sh

      - name: Setup Lean CI dependencies
        run: ../scripts/setup-lean-ci-deps.sh

      - name: Build Lean package
        run: lake build
